Change temporary file generation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@ try_cflag(){
 	flag="$1"
 
 	printf 'checking whether compiler accepts %s... ' "$flag"
-	echo "typedef int abc;" >&$tmpfd
+	echo "typedef int abc;" >"$ctmp"
 
 	if $CC "$flag" -c -o /dev/null "$ctmp" >/dev/null 2>&1
 	then
@@ -27,26 +27,11 @@ then
 	CC=cc
 fi
 
-tmpfd=5
-found=0
+irtmpdir="${TMPDIR}"/ir.$$
+mkdir "$irtmpdir" || { echo "couldn't make temporary directory" >&2; exit 1; }
+trap "rm -rf '$irtmpdir'" EXIT
 
-for i in $(seq 1 100)
-do
-	ctmp="$TMPDIR"/$i.c
-	if 2>/dev/null $tmpfd>|$ctmp
-	then
-		found=1
-		break
-	fi
-done
-
-if [ $found -eq 0 ]
-then
-	echo "couldn't find unused temporary file in $TMPDIR" >&2
-	exit 1
-fi
-
-trap "rm -f '$ctmp'" EXIT
+ctmp="$irtmpdir/1.c"
 
 echo > Makefile.cfg
 
